[package]
name = "remind_me_mcp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
remind_me_core.workspace = true
rusty_tokio.workspace = true
rusty_json.workspace = true
rusty_http.workspace = true
rusty_std.workspace = true

serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tokio.workspace = true
